// Sample data configuration - Customize this to add your own products and bundles

export const sampleProducts = [
  {
    name: 'Neural Pulse Headphones',
    slug: 'neural-pulse-headphones',
    description: 'Experience audio in a new dimension with our AI-powered noise cancellation and 3D spatial audio technology. These premium headphones deliver studio-quality sound with unmatched comfort.',
    category: 'audio',
    price: 299,
    originalPrice: 399,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
      'https://images.unsplash.com/photo-1545127398-14699f92334b?w=800',
    ],
    mainImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
    inStock: true,
    stock: 50,
    rating: 4.8,
    reviews: 245,
    features: [
      'Active Noise Cancellation with 6 microphones',
      '40-hour battery life on single charge',
      'Spatial Audio with dynamic head tracking',
      'USB-C Fast Charging - 5 min charge = 3 hours playback',
      'Premium memory foam ear cushions',
      'Multipoint Bluetooth 5.3 connectivity',
    ],
    specs: new Map([
      ['Driver Size', '40mm Neodymium'],
      ['Frequency Response', '20Hz - 20kHz'],
      ['Impedance', '32 Ohm'],
      ['Weight', '250g'],
      ['Battery Life', '40 hours'],
      ['Charging Port', 'USB-C'],
      ['Bluetooth', '5.3'],
      ['Range', '10m / 33ft'],
    ]),
    badge: 'bestseller',
    tags: ['wireless', 'premium', 'anc', 'bluetooth'],
  },
  {
    name: 'Quantum Watch Pro',
    slug: 'quantum-watch-pro',
    description: 'Next-gen smartwatch with holographic display and comprehensive biometric health tracking. Stay connected and healthy with cutting-edge technology on your wrist.',
    category: 'wearables',
    price: 499,
    originalPrice: 599,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800',
    ],
    mainImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
    inStock: true,
    stock: 30,
    rating: 4.6,
    reviews: 189,
    features: [
      'Holographic AMOLED Display',
      'Advanced Heart Rate & SpO2 Monitoring',
      'GPS + GLONASS + Galileo Tracking',
      '7-day battery life with always-on display',
      'ECG App for heart health',
      'Sleep tracking with REM detection',
    ],
    specs: new Map([
      ['Display', '1.4" AMOLED'],
      ['Resolution', '454 x 454'],
      ['Water Resistance', '5 ATM (50m)'],
      ['Sensors', 'Heart Rate, SpO2, GPS, Accelerometer, Gyroscope'],
      ['Battery', '7 days typical use'],
      ['Connectivity', 'Bluetooth 5.0, Wi-Fi'],
    ]),
    badge: 'new',
    tags: ['smartwatch', 'fitness', 'premium', 'health'],
  },
  {
    name: 'Cyber Keyboard RGB',
    slug: 'cyber-keyboard-rgb',
    description: 'Professional mechanical gaming keyboard with customizable per-key RGB lighting and premium tactile switches. Built for gamers and creators who demand the best.',
    category: 'gaming',
    price: 149,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800',
    ],
    mainImage: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
    inStock: true,
    stock: 100,
    rating: 4.7,
    reviews: 312,
    features: [
      'Cherry MX Red Mechanical Switches',
      'Per-Key RGB Backlighting with 16.8M colors',
      'Programmable Macro Keys',
      'USB Passthrough Port',
      'Detachable braided cable',
      'Aircraft-grade aluminum frame',
    ],
    specs: new Map([
      ['Switch Type', 'Cherry MX Red'],
      ['Actuation Force', '45g'],
      ['Key Rollover', 'N-Key (NKRO)'],
      ['Cable', 'Braided USB-C, 1.8m'],
      ['Polling Rate', '1000Hz'],
      ['Dimensions', '440 x 135 x 40mm'],
    ]),
    badge: '',
    tags: ['gaming', 'rgb', 'mechanical', 'keyboard'],
  },
  {
    name: 'Aurora Smart Bulbs (4-Pack)',
    slug: 'aurora-smart-bulbs',
    description: 'Transform your space with intelligent color-changing smart bulbs. 16 million colors, voice control, and sync with music for the ultimate lighting experience.',
    category: 'smart-home',
    price: 79,
    originalPrice: 99,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    ],
    mainImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    inStock: true,
    stock: 75,
    rating: 4.5,
    reviews: 156,
    features: [
      '16 million color options',
      'Voice control (Alexa, Google Assistant)',
      'Music sync mode',
      'Schedule and automation',
      '25,000 hour lifespan',
      'Energy efficient LED',
    ],
    specs: new Map([
      ['Brightness', '800 lumens'],
      ['Wattage', '9W'],
      ['Base', 'E26'],
      ['Color Temperature', '2700K - 6500K'],
      ['Connectivity', 'Wi-Fi 2.4GHz'],
      ['Lifespan', '25,000 hours'],
    ]),
    badge: '',
    tags: ['smart-home', 'lighting', 'wifi', 'voice-control'],
  },
  {
    name: 'Sonic Earbuds Pro',
    slug: 'sonic-earbuds-pro',
    description: 'True wireless earbuds with hybrid ANC, premium sound quality, and all-day battery. Perfect for music lovers and commuters.',
    category: 'audio',
    price: 199,
    originalPrice: 249,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800',
    ],
    mainImage: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800',
    inStock: true,
    stock: 60,
    rating: 4.7,
    reviews: 203,
    features: [
      'Hybrid Active Noise Cancellation',
      '8h playback + 24h with case',
      'Transparency mode',
      'IPX5 water resistance',
      'Touch controls',
      'Wireless charging case',
    ],
    specs: new Map([
      ['Driver', '10mm Dynamic'],
      ['Battery', '8h + 24h (case)'],
      ['Bluetooth', '5.2'],
      ['Water Resistance', 'IPX5'],
      ['Weight', '5g per earbud'],
      ['Charging', 'USB-C + Wireless'],
    ]),
    badge: 'bestseller',
    tags: ['wireless', 'earbuds', 'anc', 'waterproof'],
  },
  {
    name: 'Fitness Band Elite',
    slug: 'fitness-band-elite',
    description: 'Affordable fitness tracker with heart rate monitoring, sleep tracking, and 14-day battery life. Your perfect workout companion.',
    category: 'wearables',
    price: 49,
    images: [
      'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800',
    ],
    mainImage: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800',
    inStock: true,
    stock: 120,
    rating: 4.3,
    reviews: 421,
    features: [
      '24/7 Heart rate monitoring',
      'Sleep tracking',
      'Step counter',
      '14-day battery life',
      '5 ATM water resistance',
      'Multiple sport modes',
    ],
    specs: new Map([
      ['Display', '0.96" OLED'],
      ['Battery', '14 days'],
      ['Water Resistance', '5 ATM'],
      ['Sensors', 'Heart Rate, Accelerometer'],
      ['Weight', '22g'],
      ['Connectivity', 'Bluetooth 5.0'],
    ]),
    badge: '',
    tags: ['fitness', 'affordable', 'health', 'waterproof'],
  },
];

export const sampleBundles = [
  {
    name: 'Ultimate Audio Bundle',
    slug: 'ultimate-audio-bundle',
    description: 'Complete audio setup for audiophiles. Includes our best-selling headphones and premium earbuds for the perfect listening experience at home and on-the-go.',
    category: 'audio',
    price: 449,
    originalPrice: 598,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
    inStock: true,
    badge: 'popular',
    tags: ['audio', 'wireless', 'premium', 'complete'],
  },
  {
    name: 'Gaming Pro Pack',
    slug: 'gaming-pro-pack',
    description: 'Everything you need for professional gaming. RGB keyboard and premium gaming headset bundle to dominate the competition.',
    category: 'gaming',
    price: 399,
    originalPrice: 548,
    discount: 27,
    image: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800',
    inStock: true,
    badge: 'limited',
    tags: ['gaming', 'rgb', 'professional', 'esports'],
  },
  {
    name: 'Smart Home Starter Kit',
    slug: 'smart-home-starter-kit',
    description: 'Begin your smart home journey with this complete starter kit. Includes smart bulbs and voice control setup.',
    category: 'smart-home',
    price: 129,
    originalPrice: 178,
    discount: 28,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    inStock: true,
    badge: 'exclusive',
    tags: ['smart-home', 'automation', 'voice-control', 'starter'],
  },
  {
    name: 'Fitness Enthusiast Bundle',
    slug: 'fitness-enthusiast-bundle',
    description: 'Track your fitness goals with smartwatch and fitness band combo. Perfect for serious athletes.',
    category: 'wearables',
    price: 499,
    originalPrice: 648,
    discount: 23,
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800',
    inStock: true,
    badge: 'popular',
    tags: ['fitness', 'health', 'wearables', 'tracking'],
  },
];

export const testUser = {
  email: 'test@example.com',
  password: 'password123',
  name: 'Test User',
  authProvider: 'local',
};

// Category mapping for easy reference
export const categories = {
  AUDIO: 'audio',
  WEARABLES: 'wearables',
  ACCESSORIES: 'accessories',
  SMART_HOME: 'smart-home',
  GAMING: 'gaming',
};

// Badge types
export const badges = {
  NEW: 'new',
  BESTSELLER: 'bestseller',
  LIMITED: 'limited',
  POPULAR: 'popular',
  EXCLUSIVE: 'exclusive',
};
